Mobile Version Skeleton
SaeqaSultani/Portfolio-Project pull request #1
Opened 2022-07-06 16:20 UTC by SaeqaSultani

- Created a new branch according to the GitHub flow rules.
- Added a .gitignored file.
- Set up a linter for CSS and HTML .
- Added a readme file.
- Added a .html file .
- Added a .css file .
- Added a test.md file

2022-07-06 19:37 UTC, mugishasam123 requested changes
Hi  @SaeqaSultani  👋 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![alt](https://c.tenor.com/0Q8SiDHvSZIAAAAC/so-close-so-close-seth-meyers.gif)
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights

✅ Linter checks passed
✔️ Github flow was properly used
✔️ Descriptive PR title


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-06 19:37 UTC, mugishasam123 commented on index.html
> +          <img src="images/logo.png" alt="my logo"/>
- [ ] I would kindly recommend you wrap your logo in an `a` tag to make your site more engaging. so that users can click on it.

2022-07-06 19:37 UTC, mugishasam123 commented on index.html
> +         Glad to see you!</h4>
- [ ] kindly change this topic to the `h1` tag to make search engines realize it and for semantic reasons. you got this 👍

2022-07-06 19:37 UTC, mugishasam123 commented on index.html
> +             </div>
- [ ] Please you should use the `ul` tag to wrap up your icons and the `li`  tag on each individual icon to make your code semantically correct. you can check more about[ semantics](https://www.w3schools.com/html/html5_semantic_elements.asp).

2022-07-06 19:37 UTC, mugishasam123 commented on index.html
> +        <h4 class="short-presentation">I’m
- [ ] Kindly stick to Figma design as much as possible because It's an important skill that you will need in your future career. try to match colors, fonts, size,etc.


Figma design:
![image](https://user-images.githubusercontent.com/90524466/177628574-0da08037-8802-4ba7-8bd8-54f778c1e22c.png)


your design:
![image](https://user-images.githubusercontent.com/90524466/177628345-8989ec39-f8fc-41ed-9029-defb42e7c0de.png)

2022-07-07 03:17 UTC, Reem-lab approved these changes
## Hi @SaeqaSultani,👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🔥🔥

## Highlights
 - No linters error✅✅
 - Good following GitHub flow✅✅

## Optional suggestions
[ OPTIONAL ] Kindly fix the background image for the header to match the Figma design🙏🏻🙏🏻

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-11 15:33 UTC, merged