Added mobile menu to the mobile version of the  Portfolio-Project
SaeqaSultani/Portfolio-Project pull request #10
Opened 2022-07-27 08:45 UTC by SaeqaSultani

- Added a .gitignored file.
- Set up a linter for CSS ,HTML  and JavaScript.
- Added a readme file.
- Added a .html file.
- Added a .css file.
- Added a . js file.
- Added a test.md file

2022-07-27 11:20 UTC, zhadier requested changes
# Hi @SaeqaSultani  👋 

Good job so far! 🌤️ 
There are some issues that you still need to work on to go to the next project but you are almost there! 🍓 

<img src="https://media4.giphy.com/media/5wWf7GR2nhgamhRnEuA/giphy.gif"/>

## Highlights
✔️ No linter errors
✔️ Github flow was set up correctly
✔️ Professional pull request title


## Required Changes ♻️

- [ ] In your PR descriptions, kindly also mention the features you added so we know what exactly has been implemented in the FIles you mentioned

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question @zhadier so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 11:20 UTC, zhadier commented on main.js
> +});
- [ ] Great job implementing the functionality for the hamburger. But kindly refer to the images below and increase the blur effect in the background so it resembles the Figma template. As you can see the Figma mobile menu has a much darker background with a less visible backdrop.

> Figma Design

![image](https://user-images.githubusercontent.com/90556221/181234251-f2d30c4d-24e7-48e6-b73c-3c6ec74bd0a0.png)

> Your Design

![image](https://user-images.githubusercontent.com/90556221/181234332-40def86a-560b-4125-bcfb-619b0e3c3819.png)

- [ ] Additionally, kindly also implement the black horizontal line at the end of the Mobile menu like I've highlighted in the Figma template above.

2022-07-27 12:25 UTC, vechicin requested changes
# Hi @SaeqaSultani ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing some of the previous reviewer's requirements

 ## Required Changes ♻️

- [ ] You still need to tweak your PR description. It is not enough to list the files you added for this project, you need to verbally describe the features you implemented on this branch. Please do so.

_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 12:25 UTC, vechicin commented on style.css
> +}
While you did implement a previous reviewer's requirement, you're still missing some other ones that were requested.

<img width="228" alt="Screen Shot 2022-07-27 at 7 17 48" src="https://user-images.githubusercontent.com/82426682/181244847-e32063fd-0b9a-4ad4-80b6-6f327889ae98.png">

<img width="269" alt="Screen Shot 2022-07-27 at 7 18 10" src="https://user-images.githubusercontent.com/82426682/181244922-05d2a25b-2576-478c-8af9-54484f8d5d81.png">

The background is not blurred yet, and the black divider at the bottom doesn't have the correct color nor the correct positioning. Please fix them.

Additionally, I am now experiencing a horizontal scroll that makes for bad UI/UX.

<img width="227" alt="Screen Shot 2022-07-27 at 7 22 33" src="https://user-images.githubusercontent.com/82426682/181245651-942402c8-d940-4269-aedd-a8da2f55d142.png">

Please fix it as well.

2022-07-27 13:20 UTC, SaeqaSultani commented
Please kindly explain to me what is your mind about the PR description
because this is my last chance.

On Wed, Jul 27, 2022 at 4:55 PM Santiago Velosa ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @SaeqaSultani <https://github.com/SaeqaSultani> ✋,
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet. 🚨
> Highlights ⚡
>
>    - Good job implementing some of the previous reviewer's requirements
>
> Required Changes ♻️
>
>    - You still need to tweak your PR description. It is not enough to
>    list the files you added for this project, you need to verbally describe
>    the features you implemented on this branch. Please do so.
>
> *Check the comments under the review.*
> Optional suggestions 📂
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/SaeqaSultani/Portfolio-Project/pull/10#discussion_r930992358>
> :
>
> > +.internal-link-mobActive {
>
> +  width: 100%;
>
> +  margin: 0;
>
> +  padding-left: 40px !important;
>
> +  background-color: rgb(16, 37, 222) !important;
>
> +}
>
>
> While you did implement a previous reviewer's requirement, you're still
> missing some other ones that were requested.
>
> [image: Screen Shot 2022-07-27 at 7 17 48]
> <https://user-images.githubusercontent.com/82426682/181244847-e32063fd-0b9a-4ad4-80b6-6f327889ae98.png>
>
> [image: Screen Shot 2022-07-27 at 7 18 10]
> <https://user-images.githubusercontent.com/82426682/181244922-05d2a25b-2576-478c-8af9-54484f8d5d81.png>
>
> The background is not blurred yet, and the black divider at the bottom
> doesn't have the correct color nor the correct positioning. Please fix them.
>
> Additionally, I am now experiencing a horizontal scroll that makes for bad
> UI/UX.
>
> [image: Screen Shot 2022-07-27 at 7 22 33]
> <https://user-images.githubusercontent.com/82426682/181245651-942402c8-d940-4269-aedd-a8da2f55d142.png>
>
> Please fix it as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SaeqaSultani/Portfolio-Project/pull/10#pullrequestreview-1052404665>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR2XK5PCHOA6MAM42OSGYKTVWETCVANCNFSM54YXU5HA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-27 20:08 UTC, Ismailco approved these changes
### Hi @SaeqaSultani, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-27 20:08 UTC, Ismailco commented on index.html
> +            <ul class="internal-link-mob">
- [ ] [OPTIONAL] Good job implementing the requested changes, you can give the menu element's some space or remove the margin so they are closer to the edge of the page like in the Figma design

![Screenshot_20220727_210418](https://user-images.githubusercontent.com/25227022/181362618-b49c44c0-ae79-41aa-bf20-4bc4a754af88.png)

2022-07-29 07:08 UTC, merged

2022-09-17 15:37 UTC, SaeqaSultani commented
weekly Meet
Tuesday Sep 27, 2022



Organizer
***@***.***
***@***.***

Guests
***@***.*** - organizer
***@***.***
View all guest info  
https://calendar.google.com/calendar/event?action=VIEW&eid=M3IwN2NjaHE4NmVva2pkajNnODZkdjlrdGFfMjAyMjA5MjcgcmVwbHkrYXIyeGs1bXA1YWJ2bGY1dmdnaXQ1ZzZhNXpxc3ZldmJuaGhlNWlvYzV1QHJlcGx5LmdpdGh1Yi5jb20&tok=MjMjc2FlcWEuc3VsdGFuaUBnbWFpbC5jb20zYzNkMmUxMDMyMWFhZjViNWUzMDFmMmEyOWUxNGIyMmRiYmQyYmU0&ctz=Asia%2FKabul&hl=en&es=0

Reply for ***@***.***  
and view more details  
https://calendar.google.com/calendar/event?action=VIEW&eid=M3IwN2NjaHE4NmVva2pkajNnODZkdjlrdGFfMjAyMjA5MjcgcmVwbHkrYXIyeGs1bXA1YWJ2bGY1dmdnaXQ1ZzZhNXpxc3ZldmJuaGhlNWlvYzV1QHJlcGx5LmdpdGh1Yi5jb20&tok=MjMjc2FlcWEuc3VsdGFuaUBnbWFpbC5jb20zYzNkMmUxMDMyMWFhZjViNWUzMDFmMmEyOWUxNGIyMmRiYmQyYmU0&ctz=Asia%2FKabul&hl=en&es=0
Your attendance is optional.

~~//~~
Invitation from Google Calendar: https://calendar.google.com/calendar/

You are receiving this email because you are an attendee on the event. To  
stop receiving future updates for this event, decline this event.

Forwarding this invitation could allow any recipient to send a response to  
the organizer, be added to the guest list, invite others regardless of  
their own invitation status, or modify your RSVP.

Learn more https://support.google.com/calendar/answer/37135#forwarding